### ISSUE TITLE
Is this repo necessary?

### ISSUE THREAD

**Issue by LOZORD** [UW-UPL/UPL_Interview-Prep_10-1-15#10]
Sorry @ranman166, I did not realize that @Ricky54326 had already written solutions. Do you guys think that this repo is still necessary? I'm fine trashing it if you agree.

See http://pages.cs.wisc.edu/~riccardo/interviewprep.html

**Comment by Ricky54326** [comment]
Yeah we can trash it if you guys want. Don't care either way.


On Feb 15, 2016, at 11:40 AM, Leo Rudberg <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry @ranman166<https://github.com/ranman166>, I did not realize that @Ricky54326<https://github.com/Ricky54326> had already written solutions. Do you guys think that this repo is still necessary? I'm fine trashing it if you agree.

See http://pages.cs.wisc.edu/~riccardo/interviewprep.html<http://pages.cs.wisc.edu/%7Ericcardo/interviewprep.html>

-

**Comment by ranman166** [comment]
Sure doesn't matter to me

**Comment by ranman166** [comment]
oops i closed it

**Comment by LOZORD** [comment]
Ok I'll trash it
